# Generated by Django 3.1.12 on 2025-06-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20250624_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='shipping_address',
        ),
    ]
