# Generated by Django 3.1.12 on 2025-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
