services:
  - type: web
    name: farmlink-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn farm_link.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false